name: Nextcloud

on:
  push:
    schedule:
      - cron: '0 */8 * * *'

jobs:
  build-nextcloud-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login in Docker
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERUSERNAME }}
         password: ${{ secrets.DOCKERAPIKEY }}
      - name: Create docker image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="rjpadilla/nextcloud"
          source .github/workflows/utils.sh
          alpine_arm_sha=$(get_manifest_sha "$repo:latest" "arm")
          echo "$repo arm"
          echo $alpine_arm_sha
          nextcloud_arm_sha=$(get_manifest_sha "nextcloud:latest" "arm")
          echo "nextcloud arm"
          echo $nextcloud_arm_sha
          flag_arm=$(is_base "$repo@"$alpine_arm_sha "nextcloud@"$nextcloud_arm_sha)
          echo "flag arm"
          echo $flag_arm
          alpine_amd64_sha=$(get_manifest_sha "$repo:latest" "amd64")
          echo $alpine_amd64_sha
          nextcloud_amd64_sha=$(get_manifest_sha "nextcloud:latest" "amd64")
          echo $nextcloud_amd64_sha
          flag_amd64=$(is_base "$repo@"$alpine_amd64_sha "nextcloud@"$nextcloud_amd64_sha)
          echo "flag amd64"
          echo $flag_amd64
          alpine_arm64_sha=$(get_manifest_sha "$repo:latest" "arm64")
          echo "alpine arm64"
          echo $alpine_arm64_sha
          nextcloud_arm64_sha=$(get_manifest_sha "nextcloud:latest" "arm64")
          echo "nextcloud arm64"
          echo $nextcloud_arm64_sha
          flag_arm64=$(is_base "$repo@"$alpine_arm64_sha "nextcloud@"$nextcloud_arm64_sha)
          echo "flag arm64"
          echo $flag_arm64
          version2=$(image_version nextcloud:latest)
          echo "repo version is $version2"
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          build_image "$repo:latest" arm "$repo"
          build_image "$repo:latest" amd64 "$repo"
          build_image "$repo:latest" arm64 "$repo"
          flag=$(compare "$repo@"$alpine_arm_sha "nextcloud@"$nextcloud_arm_sha "$repo@"$alpine_amd64_sha "nextcloud@"$nextcloud_amd64_sha "$repo@"$alpine_arm64_sha "nextcloud@"$nextcloud_arm64_sha "nextcloud" "nextcloud-tags:amd64")
          echo $flag
          deploy_image "$repo" arm
          deploy_image "$repo" amd64
          deploy_image "$repo" arm64
          tag=$(date +%Y%m%d%H%M)
          tag2="latest"
          echo $tag
          create_manifest $repo $tag $tag2 $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
          docker manifest inspect $repo:$tag
          docker manifest inspect $repo:$tag2
          if [[ $flag == true ]]; then
            docker manifest push $repo:$tag; docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi 