name: Nextcloud

on:
  push:
    schedule:
      - cron: '0 */8 * * *'

jobs:
  build-nextcloud-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login in Docker
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERUSERNAME }}
         password: ${{ secrets.DOCKERAPIKEY }}
      - name: Create docker image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="rjpadilla/nextcloud"
          source .github/workflows/utils.sh
          treehouses_nextcloud_arm_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "arm")
          echo "treehouses nextcloud arm"
          echo $treehouses_nextcloud_arm_sha
          nextcloud_arm_sha=$(get_manifest_sha "nextcloud:latest" "arm" "v7")
          echo "nextcloud arm"
          echo $nextcloud_arm_sha
          flag_arm=$(is_base "treehouses/nextcloud@"$treehouses_nextcloud_arm_sha "nextcloud@"$nextcloud_arm_sha)
          echo "flag arm"
          echo $flag_arm
          nextcloud_arm64_sha=$(get_manifest_sha "nextcloud:latest" "arm64" "v7")
          echo "nextcloud64 arm"
          echo $nextcloud_arm64_sha
          treehouses_nextcloud_arm64_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "arm64")
          echo "treehouses nextcloud arm64"
          echo $treehouses_nextcloud_arm64_sha
          flag_arm64=$(is_base "nextcloud@"$nextcloud_arm64_sha "treehouses/nextcloud@"$treehouses_nextcloud_arm64_sha)
          echo "flag arm64"
          echo $flag_arm64
          nextcloud_amd64_sha=$(get_manifest_sha "nextcloud:latest" "amd64" "v7")
          echo "nextcloud amd64"
          echo $nextcloud_amd64_sha
          treehouses_nextcloud_amd64=$(get_manifest_sha "treehouses/nextcloud:latest" "amd64")
          echo "treehouses nextcloud amd64"
          echo $treehouses_nextcloud_amd64
          flag_amd64=$(is_base "nextcloud@"$nextcloud_amd64 "treehouses/nextcloud@"$treehouses_nextcloud_amd64_sha)
          echo "flag amd64"
          echo $flag_amd64
          echo 4
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          build_image "treehouses/nextcloud:latest" arm "$repo"
          build_image "treehouses/nextcloud:latest" amd64 "$repo"
          build_image "treehouses/nextcloud:latest" arm64 "$repo"
          echo 3
          flag=$(compare "treehouses/nextcloud@"$treehouses_nextcloud_arm_sha "nextcloud@"$nextcloud_arm_sha "treehouses/nextcloud@"$treehouses_nextcloud_amd64_sha "nextcloud@"$nextcloud_amd64_sha "treehouses/nextcloud@"$treehouses_nextcloud__arm64_sha "nextcloud@"$nextcloud_arm64_sha)
          echo $flag
          deploy_image "$repo" arm
          deploy_image "$repo" arm64
          deploy_image "$repo" amd64
          echo 2
          tag=$(date +%Y%m%d%H%M)
          tag2="latest"
          echo $tag
          echo 1
          if [[ $flag == true ]]; then
            docker manifest push $repo:$tag; docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi
          echo 0
          create_manifest $repo $tag $tag2 $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
          docker manifest inspect $repo:$tag
          docker manifest inspect $repo:$tag2
