name: Nextcloud

on:
  push:
    schedule:
      - cron: '0 */8 * * *'

jobs:
  build-nextcloud-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login in Docker
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERUSERNAME }}
         password: ${{ secrets.DOCKERAPIKEY }}
      - name: Get manifest shas
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="rjpadilla/nextcloud"
          source sha_function.sh
          nextcloud_arm_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "arm")
          echo "nextcloud arm"
          echo $nextcloud_arm_sha
          nextcloud_amd64_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "amd64")
          echo "nextcloud amd64"
          echo $nextcloud_amd64_sha
          nextcloud_arm64_sha=$(get_manifest_sha "treehouses/nextcloud" "arm64")
          echo $nextcloud_arm64_sha
          echo $nextcloud_arm64_sha
      - name: Create docker images
        run: |
          flag=$(compare_sha "$nextcloud_arm_sha" "$nextcloud_arm64_sha" "nextcloud_amd64_sha")
          echo $flag
          tag="$(date +%Y%m%d%H%M)"
          tag2="latest"
          echo $tag
          docker manifest create $repo:$tag "treehouses/nextcloud@"$nextcloud_arm_sha "treehouses/nextcloud@"$nextcloud_arm64_sha "treehouses/nextcloud@"$nextcloud_amd64_sha
          docker manifest create $repo:$tag2 "treehouses/nextcloud@"$nextcloud_arm_sha "treehouses/nextcloud@"$nextcloud_arm64_sha "treehouses/nextcloud@"$nextcloud_amd64_sha
          docker manifest annotate $repo:$tag2 "treehouses/nextcloud@"$nextcloud_arm_sha --arch arm
          docker manifest annotate $repo:$tag "treehouses/nextcloud@"$nextcloud_arm64_sha --arch arm64
          docker manifest annotate $repo:$tag2 "treehouses/nextcloud@"$nextcloud_arm64_sha --arch arm64
          docker manifest annotate $repo:$tag "treehouses/nextcloud@"$nextcloud_arm_sha --arch arm
          docker manifest inspect $repo:$tag
          docker manifest inspect $repo:$tag2
          if [[ $flag == true ]]; then
            docker manifest push $repo:$tag; docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi