name: Nextcloud

on:
  push:
    schedule:
      - cron: '0 */8 * * *'

jobs:
  build-nextcloud-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login in Docker
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERUSERNAME }}
         password: ${{ secrets.DOCKERAPIKEY }}
      - name: Create docker image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="rjpadilla/nextcloud"
          source .github/workflows/utils.sh
          treehouses_arm_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "arm")
          echo "treehouses arm"
          echo $treehouses_arm_sha
          nextcloud_arm_sha=$(get_manifest_sha "nextcloud:latest" "arm")
          echo "nextcloud arm"
          echo $nextcloud_arm_sha
          flag_arm=$(is_base "treehouses/nextcloud@"$treehouses_arm_sha "nextcloud@"$nextcloud_arm_sha)
          echo "flag arm"
          echo $flag_arm
          treehouses_arm64_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "arm64")
          echo "treehouses arm64"
          echo $treehouses_arm64_sha
          nextcloud_arm64_sha=$(get_manifest_sha "nextcloud:latest" "arm64")
          echo "nextcloud arm64"
          echo $nextcloud_arm64_sha
          flag_arm64=$(is_base "treehouses/nextcloud@"$treehouses_arm64_sha "nextcloud@"$nextcloud_arm64_sha)
          echo "flag arm64"
          echo $flag_arm64
          treehouses_amd64_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "amd64")
          echo "treehouses amd64"
          echo $treehouses_amd64_sha
          nextcloud_amd64_sha=$(get_manifest_sha "nextcloud:latest" "amd64")
          echo "nextcloud amd64"
          echo $nextcloud_amd64_sha
          flag_amd64=$(is_base "treehouses/nextcloud@"$treehouses_amd64_sha "nextcloud@"$nextcloud_amd64_sha)
          echo "flag amd64"
          echo $flag_amd64