name: Nextcloud

on:
  push:
    schedule:
      - cron: '0 */8 * * *'

jobs:
  build-nextcloud-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login in Docker
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERUSERNAME }}
         password: ${{ secrets.DOCKERAPIKEY }}
      - name: Create docker image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="rjpadilla/nextcloud"
          source .github/workflows/utils.sh
          treehouses_arm_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "arm")
          echo "treehouses arm"
          echo $treehouses_arm_sha
          nextcloud_arm_sha=$(get_manifest_sha "nextcloud:latest" "arm")
          echo "nextcloud arm"
          echo $nextcloud_arm_sha
          flag_arm=$(is_base "treehouses/nextcloud@"$treehouses_arm_sha "nextcloud@"$nextcloud_arm_sha)
          echo "flag arm"
          echo $flag_arm
          