name: Nextcloud

on:
  push:
    schedule:
      - cron: '0 */8 * * *'

jobs:
  build-nextcloud-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login in Docker
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERUSERNAME }}
         password: ${{ secrets.DOCKERAPIKEY }}
      - name: Create docker image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="rjpadilla/nextcloud"
          source .github/workflows/utils.sh
          nextcloud_x86_sha=$(get_variant_sha "nextcloud" "latest" "amd64")
          echo "nextcloud amd64"
          echo $nextcloud_x86_sha
          variant_nextcloud_x86_sha=$(get_manifest_sha "$repo:latest" "amd64")
          echo "treehouses/nextcloud amd64"
          echo $variant_nextcloud_x86_sha
          arm_sha=$(get_tag_sha "nextcloud" "latest")
          echo $arm_sha
          variant_rpi_sha=$(get_manifest_sha "$repo:latest" "arm")
          echo $variant_rpi_sha
          nextcloud_arm64_sha=$(get_variant_sha "nextcloud" "latest" "arm64")
          echo $nextcloud_arm64_sha
          variant_nextcloud_arm64_sha=$(get_manifest_sha "$repo:latest" "arm64")
          echo $variant_nextcloud_arm64_sha
          flag=$(compare_sha  "$nextcloud_x86_sha" "$variant_nextcloud_x86_sha" "$arm_sha" "$variant_rpi_sha" "$nextcloud_arm64_sha" "$variant_nextcloud_arm64_sha")
          echo $flag
          tag="3.12-$(date +%Y%m%d%H%M)"
          tag2="latest"
          echo $tag
          create_manifests $repo $tag "nextcloud@"$nextcloud_x86_sha "nextcloud@"$arm_sha "nextcloud@"$nextcloud_arm64_sha
          # docker manifest create $repo:$tag "nextcloud@"$nextcloud_x86_sha "nextcloud@"$arm_sha "nextcloud@"$nextcloud_arm64_sha
          # docker manifest create $repo:latest "nextcloud@"$nextcloud_x86_sha "nextcloud@"$arm_sha "nextcloud@"$nextcloud_arm64_sha
          # docker manifest annotate $repo:latest "nextcloud@"$arm_sha --arch arm
          # docker manifest annotate $repo:$tag "nextcloud@"$nextcloud_arm64_sha --arch arm64
          # docker manifest annotate $repo:latest "nextcloud@"$nextcloud_arm64_sha --arch arm64
          # docker manifest annotate $repo:$tag "nextcloud@"$arm_sha --arch arm
          # docker manifest inspect $repo:$tag
          # docker manifest inspect $repo:$tag2
          if [[ $flag == true ]]; then
            docker manifest push $repo:$tag; docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi